### PR TITLE
Change Version to match rails5 branch version of client_side_validations

### PR DESCRIPTION
**Pull request by SebDE**

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks but I will not merge this one.

I will wait until the official release of Rails 5 to merge the `rails5` branch on th `master` and release a new gem

**Comment by SebDE** [comment]
No problem - works just fine out of the box - with only one little deprecated warning (same as in client_side_validations gem) - Many thanks for your work !

**Comment by tagliala** [comment]
@SebDE thanks

Could you please post the warning?

**Comment by SebDE** [comment]
Here it is:
> DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in included at /Users/sebastian/.rvm/gems/ruby-2.3.0@rails5.0/bundler/gems/client_side_validations-simple_form-4ce6f834f0cd/lib/client_side_validations/simple_form/form_builder.rb:6)

**Comment by tagliala** [comment]
Please giva a try to 

```rb
gem 'client_side_validations-simple_form', github: 'DavyJonesLocker/client_side_validations', branch: 'rails5'
```

**Comment by SebDE** [comment]
Worked perfect for me - no warnings :+1: 

Many thanks !

**Pull request closed without merging**
